/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Language */

#ifndef _Included_ch_usi_si_seart_treesitter_Language
#define _Included_ch_usi_si_seart_treesitter_Language
#ifdef __cplusplus
extern "C" {
#endif
#undef ch_usi_si_seart_treesitter_Language_INVALID
#define ch_usi_si_seart_treesitter_Language_INVALID 0LL
/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    ada
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_ada
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    bash
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_bash
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    c
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_c
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    clojure
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_clojure
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    commonLisp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_commonLisp
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    cMake
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_cMake
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    cSharp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_cSharp
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    cpp
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_cpp
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    css
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_css
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    dart
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_dart
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    dockerfile
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_dockerfile
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    dot
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_dot
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    elixir
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_elixir
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    elm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_elm
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    embeddedTemplate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_embeddedTemplate
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    erlang
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_erlang
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    fortran
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_fortran
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    go
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_go
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    graphQl
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_graphQl
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    haskell
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_haskell
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    html
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_html
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    java
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_java
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    javascript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_javascript
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    json
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_json
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    julia
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_julia
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    kotlin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_kotlin
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    latex
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_latex
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    lua
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_lua
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    markdown
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_markdown
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    nix
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_nix
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    objectiveC
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_objectiveC
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    ocaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_ocaml
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    pascal
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_pascal
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    php
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_php
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    python
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_python
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    ruby
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_ruby
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    r
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_r
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    racket
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_racket
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    rust
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_rust
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    scala
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_scala
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    scheme
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_scheme
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    scss
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_scss
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    svelte
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_svelte
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    swift
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_swift
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    toml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_toml
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    tsx
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_tsx
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    typescript
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_typescript
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    vue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_vue
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    yaml
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_yaml
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Language
 * Method:    wasm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Language_wasm
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
