/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Parser_Builder */

#ifndef _Included_ch_usi_si_seart_treesitter_Parser_Builder
#define _Included_ch_usi_si_seart_treesitter_Parser_Builder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Parser_Builder
 * Method:    build
 * Signature: (Lch/usi/si/seart/treesitter/Language;)Lch/usi/si/seart/treesitter/Parser;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_Parser_00024Builder_build
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
