/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_version_TreeSitter */

#ifndef _Included_ch_usi_si_seart_treesitter_version_TreeSitter
#define _Included_ch_usi_si_seart_treesitter_version_TreeSitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_version_TreeSitter
 * Method:    getCurrentABIVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_version_TreeSitter_getCurrentABIVersion
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_version_TreeSitter
 * Method:    getMinimumABIVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_version_TreeSitter_getMinimumABIVersion
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
