/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_printer_DotGraphPrinter */

#ifndef _Included_ch_usi_si_seart_treesitter_printer_DotGraphPrinter
#define _Included_ch_usi_si_seart_treesitter_printer_DotGraphPrinter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_printer_DotGraphPrinter
 * Method:    write
 * Signature: (Ljava/io/File;)V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_printer_DotGraphPrinter_write
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
