/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_LookaheadIterator */

#ifndef _Included_ch_usi_si_seart_treesitter_LookaheadIterator
#define _Included_ch_usi_si_seart_treesitter_LookaheadIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_LookaheadIterator
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_LookaheadIterator_delete
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_LookaheadIterator
 * Method:    next
 * Signature: ()Lch/usi/si/seart/treesitter/Symbol;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_LookaheadIterator_next
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
