/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Tree */

#ifndef _Included_ch_usi_si_seart_treesitter_Tree
#define _Included_ch_usi_si_seart_treesitter_Tree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Tree
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_Tree_delete
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Tree
 * Method:    edit
 * Signature: (Lch/usi/si/seart/treesitter/InputEdit;)V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_Tree_edit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Tree
 * Method:    getRootNode
 * Signature: ()Lch/usi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_Tree_getRootNode
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Tree
 * Method:    clone
 * Signature: ()Lch/usi/si/seart/treesitter/Tree;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_Tree_clone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
