/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Parser */

#ifndef _Included_ch_usi_si_seart_treesitter_Parser
#define _Included_ch_usi_si_seart_treesitter_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Parser_malloc
  (JNIEnv *, jclass);

/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_Parser_close
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    setLanguage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_Parser_setLanguage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    getTimeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Parser_getTimeout
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    setTimeout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_Parser_setTimeout
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    parseBytes
 * Signature: ([BI)J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Parser_parseBytes___3BI
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     ch_usi_si_seart_treesitter_Parser
 * Method:    parseBytes
 * Signature: ([BILch/usi/si/seart/treesitter/Tree;)J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Parser_parseBytes___3BILch_usi_si_seart_treesitter_Tree_2
  (JNIEnv *, jobject, jbyteArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
