/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_Query */

#ifndef _Included_ch_usi_si_seart_treesitter_Query
#define _Included_ch_usi_si_seart_treesitter_Query
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    malloc
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ch_usi_si_seart_treesitter_Query_malloc
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_Query_delete
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    countStrings
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_Query_countStrings
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    countCaptures
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_Query_countCaptures__
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    countCaptures
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_Query_countCaptures__J
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    countPatterns
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_Query_countPatterns
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_Query
 * Method:    getCaptureName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_usi_si_seart_treesitter_Query_getCaptureName
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
