/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_usi_si_seart_treesitter_TreeCursor */

#ifndef _Included_ch_usi_si_seart_treesitter_TreeCursor
#define _Included_ch_usi_si_seart_treesitter_TreeCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    delete
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_delete
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_getCurrentDepth
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentNode
 * Signature: ()Lch/usi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_getCurrentNode
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentFieldName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_getCurrentFieldName
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentTreeCursorNode
 * Signature: ()Lch/usi/si/seart/treesitter/TreeCursorNode;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_getCurrentTreeCursorNode
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    gotoFirstChild
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_gotoFirstChild__
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    gotoFirstChild
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_gotoFirstChild__I
  (JNIEnv *, jobject, jint);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    gotoFirstChild
 * Signature: (Lch/usi/si/seart/treesitter/Point;)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_gotoFirstChild__Lch_usi_si_seart_treesitter_Point_2
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    gotoNextSibling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_gotoNextSibling
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    gotoParent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_gotoParent
  (JNIEnv *, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    gotoNode
 * Signature: (Lch/usi/si/seart/treesitter/Node;)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_gotoNode
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    reset
 * Signature: (Lch/usi/si/seart/treesitter/TreeCursor;)Z
 */
JNIEXPORT jboolean JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_reset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     ch_usi_si_seart_treesitter_TreeCursor
 * Method:    clone
 * Signature: ()Lch/usi/si/seart/treesitter/TreeCursor;
 */
JNIEXPORT jobject JNICALL Java_ch_usi_si_seart_treesitter_TreeCursor_clone
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
