/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usi_si_seart_treesitter_TreeCursor */

#ifndef _Included_usi_si_seart_treesitter_TreeCursor
#define _Included_usi_si_seart_treesitter_TreeCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    malloc
 * Signature: (Lusi/si/seart/treesitter/Node;)J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_TreeCursor_malloc
  (JNIEnv *, jclass, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentNode
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_TreeCursor_getCurrentNode
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentFieldName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usi_si_seart_treesitter_TreeCursor_getCurrentFieldName
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    getCurrentTreeCursorNode
 * Signature: ()Lusi/si/seart/treesitter/TreeCursorNode;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_TreeCursor_getCurrentTreeCursorNode
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    gotoFirstChild
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_TreeCursor_gotoFirstChild
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    gotoNextSibling
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_TreeCursor_gotoNextSibling
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeCursor
 * Method:    gotoParent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_TreeCursor_gotoParent
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
