/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usi_si_seart_treesitter_Node */

#ifndef _Included_usi_si_seart_treesitter_Node
#define _Included_usi_si_seart_treesitter_Node
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getChild
 * Signature: (I)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getChild
  (JNIEnv *, jobject, jint);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getChildByFieldName
 * Signature: (Ljava/lang/String;)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getChildByFieldName
  (JNIEnv *, jobject, jstring);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getChildCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_usi_si_seart_treesitter_Node_getChildCount
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getDescendantForByteRange
 * Signature: (II)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getDescendantForByteRange
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getEndByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_usi_si_seart_treesitter_Node_getEndByte
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getEndPoint
 * Signature: ()Lusi/si/seart/treesitter/Point;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getEndPoint
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getFieldNameForChild
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usi_si_seart_treesitter_Node_getFieldNameForChild
  (JNIEnv *, jobject, jint);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getFirstChildForByte
 * Signature: (I)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getFirstChildForByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getFirstNamedChildForByte
 * Signature: (I)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getFirstNamedChildForByte
  (JNIEnv *, jobject, jint);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getNodeString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usi_si_seart_treesitter_Node_getNodeString
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getNextNamedSibling
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getNextNamedSibling
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getNextSibling
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getNextSibling
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getPrevNamedSibling
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getPrevNamedSibling
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getPrevSibling
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getPrevSibling
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getParent
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getParent
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getStartByte
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_usi_si_seart_treesitter_Node_getStartByte
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getStartPoint
 * Signature: ()Lusi/si/seart/treesitter/Point;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Node_getStartPoint
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    getType
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usi_si_seart_treesitter_Node_getType
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    hasError
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Node_hasError
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    isExtra
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Node_isExtra
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    isMissing
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Node_isMissing
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    isNamed
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Node_isNamed
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    isNull
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Node_isNull
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Node
 * Method:    equals
 * Signature: (Lusi/si/seart/treesitter/Node;Lusi/si/seart/treesitter/Node;)Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Node_equals
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
