/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usi_si_seart_treesitter_Parser */

#ifndef _Included_usi_si_seart_treesitter_Parser
#define _Included_usi_si_seart_treesitter_Parser
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usi_si_seart_treesitter_Parser
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_Parser_malloc
  (JNIEnv *, jclass);

/*
 * Class:     usi_si_seart_treesitter_Parser
 * Method:    setLanguage
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_Parser_setLanguage
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     usi_si_seart_treesitter_Parser
 * Method:    parseBytes
 * Signature: (J[BI)J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_Parser_parseBytes__J_3BI
  (JNIEnv *, jclass, jlong, jbyteArray, jint);

/*
 * Class:     usi_si_seart_treesitter_Parser
 * Method:    parseBytes
 * Signature: (JJ[BI)J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_Parser_parseBytes__JJ_3BI
  (JNIEnv *, jclass, jlong, jlong, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
