/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usi_si_seart_treesitter_Tree */

#ifndef _Included_usi_si_seart_treesitter_Tree
#define _Included_usi_si_seart_treesitter_Tree
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usi_si_seart_treesitter_Tree
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_Tree_close
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_Tree
 * Method:    edit
 * Signature: (Lusi/si/seart/treesitter/InputEdit;)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_Tree_edit
  (JNIEnv *, jobject, jobject);

/*
 * Class:     usi_si_seart_treesitter_Tree
 * Method:    getRootNode
 * Signature: ()Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_Tree_getRootNode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
