/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usi_si_seart_treesitter_QueryCursor */

#ifndef _Included_usi_si_seart_treesitter_QueryCursor
#define _Included_usi_si_seart_treesitter_QueryCursor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usi_si_seart_treesitter_QueryCursor
 * Method:    malloc
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_QueryCursor_malloc
  (JNIEnv *, jclass);

/*
 * Class:     usi_si_seart_treesitter_QueryCursor
 * Method:    execute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_QueryCursor_execute
  (JNIEnv *, jobject);

/*
 * Class:     usi_si_seart_treesitter_QueryCursor
 * Method:    nextMatch
 * Signature: ()Lusi/si/seart/treesitter/QueryMatch;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_QueryCursor_nextMatch
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
