/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class usi_si_seart_treesitter_TreeSitter */

#ifndef _Included_usi_si_seart_treesitter_TreeSitter
#define _Included_usi_si_seart_treesitter_TreeSitter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    parserDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_parserDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryNew
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryNew
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryCaptureName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryCaptureName
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryStringCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryStringCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryCaptureCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryCaptureCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryPatternCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryPatternCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryCursorDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryCursorDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryCursorNew
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryCursorNew
  (JNIEnv *, jclass);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryCursorExec
 * Signature: (JJLusi/si/seart/treesitter/Node;)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryCursorExec
  (JNIEnv *, jclass, jlong, jlong, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    queryCursorNextMatch
 * Signature: (J)Lusi/si/seart/treesitter/QueryMatch;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_TreeSitter_queryCursorNextMatch
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorNew
 * Signature: (Lusi/si/seart/treesitter/Node;)J
 */
JNIEXPORT jlong JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorNew
  (JNIEnv *, jclass, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorCurrentTreeCursorNode
 * Signature: (J)Lusi/si/seart/treesitter/TreeCursorNode;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorCurrentTreeCursorNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorCurrentFieldName
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorCurrentFieldName
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorCurrentNode
 * Signature: (J)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorCurrentNode
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorGotoFirstChild
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorGotoFirstChild
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorGotoNextSibling
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorGotoNextSibling
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeCursorGotoParent
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeCursorGotoParent
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeDelete
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeDelete
  (JNIEnv *, jclass, jlong);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeEdit
 * Signature: (JLusi/si/seart/treesitter/InputEdit;)V
 */
JNIEXPORT void JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeEdit
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     usi_si_seart_treesitter_TreeSitter
 * Method:    treeRootNode
 * Signature: (J)Lusi/si/seart/treesitter/Node;
 */
JNIEXPORT jobject JNICALL Java_usi_si_seart_treesitter_TreeSitter_treeRootNode
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
